### ISSUE TITLE
Allow reviewers to edit or delete internal comments

### ISSUE THREAD

**Issue by abbyphoenix** [forem/cfp-app#28]
We already allow reviewers to delete their rating on a proposal after they give it, via the little trash can here: 
![image](https://user-images.githubusercontent.com/4975727/123689733-6b82bc00-d808-11eb-8e23-4a3fceaf831a.png)

Presumably, this would be so that they can re-rate it after getting more information on it, but it's also there in case someone clicked on a specific rating by mistake.

Can we also make it an option for reviewers to be able to either _edit_ or _delete_ their internal comments here? 
![image](https://user-images.githubusercontent.com/4975727/123689911-a389ff00-d808-11eb-9ed2-6a0b79f8f811.png)

Several of our reviewers are on their first program committee, and may want to amend their comments to the rest of the team and/or delete them entirely after reading other internal comments. 

**Editing to tag @joshpuetz / @fdoxyz / @nickytonline!**

**Comment by joshpuetz** [comment]
Adding `delete` functionality would be a lot less work than `edit` functionality. Here's my reasoning:

- With an `edit` function we need to present form field with the comment loaded inline, and we may want to track and display when the comment was last edited.

- With a `delete` function we just need to give the user a button or link to delete a comment, and an alert to confirm they really do want to delete said comment. We may want to also display a note that a comment was deleted, but we won't need to worry about inline editing.

How much do we want to work on this?

**Comment by abbyphoenix** [comment]
I feel like it's such a limited use case that I'd go with delete! If it was me and I was just wanting to make a small change, I'd use the "do you really want to delete" alert as my trigger to go ahead and copy my original comment, so that I can delete, paste it in a new comment, and then make my edit from there. I think that's fine.
