### ISSUE TITLE
Add Gender description field

### ISSUE THREAD

**Issue by joshpuetz** [forem/cfp-app#7]
Single-select (radio buttons), required field:
- Female
- Male
- Non-binary
- Prefer not to answer
- Other (describe below) (Can this trigger a new short answer field if selected?)

**Comment by joshpuetz** [comment]
@abbyphoenix CFP app recently added some demographic questions in PR https://github.com/rubycentral/cfp-app/pull/218, including pronouns. Would this work for our requirements? Unlike our RFC there's no user short answer field. Here's what it looks like:

<img width="1014" alt="CleanShot 2021-06-08 at 10 28 21@2x" src="https://user-images.githubusercontent.com/37842/121214087-6bfce800-c844-11eb-9cd5-c50eccf0e760.png">

**Comment by abbyphoenix** [comment]
I think this is fine -- @SGGregory, do you foresee any issues from the CodeNewbie community that would make a pronoun single select form like the above (in lieu of asking proposers to write in their gender) not okay?

**Comment by SGGregory** [comment]
I think that this approach is fine!

**Comment by joshpuetz** [comment]
Closing in favor of upstream solution
