### ISSUE TITLE
Add Ethnicity description field

### ISSUE THREAD

**Issue by joshpuetz** [forem/cfp-app#8]
Multiple-select (checkboxes), required field
- Asian or Pacific Islander
- Black or African American
- Hispanic or Latino
- Native American or American Indian
- White
- Prefer not to answer
Descriptive text: “Please check all that apply.”

**Comment by joshpuetz** [comment]
@abbyphoenix CFP-app recently added some demographic questions in PR https://github.com/rubycentral/cfp-app/pull/218, one of which includes ethnicity. Would this work for our purposes? Unlike our RFC, this field is single select without any short answer field:

<img width="1025" alt="CleanShot 2021-06-08 at 10 31 03@2x" src="https://user-images.githubusercontent.com/37842/121214444-be3e0900-c844-11eb-9761-2e6b97796eac.png">

**Comment by abbyphoenix** [comment]
I think this is fine -- @SGGregory, do you foresee any issues from the CodeNewbie community that would make a single select form like the above not okay?

**Comment by SGGregory** [comment]
Agree — this should be fie

**Comment by joshpuetz** [comment]
Closing in favor of upstream solution
